Created managment command to setup component basic structure
EmilStenstrom/django-components pull request #175
Opened 2022-09-04 00:07 UTC by ah7255703

2022-09-04 14:05 UTC, EmilStenstrom requested changes
Hi! Thank you for taking on the task of generating components with a management command! I've gone through the code and left (a lot of) comments. Don't be discouraged, I'm just eager to get all the details right in this library! :)

Clever trick to use Django's template library to generate the component file! ⭐ 

Before including this, I'd like to see some tests. Otherwise we might inadvertently break this in the future! 

Let me know if you need any help with this, I'd happily merge this with the changes suggested!

2022-09-04 14:07 UTC, EmilStenstrom commented on django_components/management/commands/createcomponent.py
> +            )
The template file references style.css, and script.js. Do you agree that the default files should have those names aswell?

2022-09-04 19:46 UTC, ah7255703 commented
thanks for the explanation but i think we've  got your attention to such feature i will work on these fixes and thank you for ur kind response

2022-09-04 19:49 UTC, ah7255703 commented on django_components/management/commands/createcomponent.py
> +        with open(THIS_DIR / "templates" / "{comp_name}.py.txt") as file:
i thought the template rendered would take care of the file name but i forgot to remove the brackets

2022-10-16 06:38 UTC, EmilStenstrom commented
ping @ah7255703 - Did you have time to look at the suggestions above?

2022-10-27 23:36 UTC, ah7255703 commented
> ping @ah7255703 - Did you have time to look at the suggestions above?

Ok, i currently have no time these days
Soon will be done

2023-03-24 21:27 UTC, closed without merging